[package]
name = "data_type"
version = "0.1.0"
authors = ["张银杰 <zhangyinjie@shizhuang-inc.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
